### PR TITLE
Remove VERIFY_DEPLOYMENT_USER

### PR DESCRIPTION
**Pull request by AmalChandru**

### CODE REVIEW

**Comment by AmalChandru** [comment]
@jugnu-appveen

**Review by jugnu-appveen — CHANGES_REQUESTED** [review]
need to remove the complete logic

**Comment by AmalChandru** [comment]
Closing this PR since the recently merged ENV changes is causing merge conflicts

**Comment by AmalChandru** [comment]
Closing this PR since the recently merged ENV changes is causing merge conflicts

**Pull request closed without merging**
